Display warnings as notifications
dotscene-gmbh/dotcube-app pull request #9
Opened 2023-05-22 13:34 UTC by flodieder

As discussed in the [OKR](https://github.com/dotscene-gmbh/dotcube/issues/411) for improving the user feedback during the scan, we want the app to display notifications for the warnings. This PR addresses exactly this issue by adding a notification that is shown if a warning pop ups.

2023-05-26 07:35 UTC, floriankramer requested changes
Mostly looks good, there's a couple minor things that need cleanup.

2023-05-26 07:35 UTC, floriankramer commented on DroneController/app/src/main/AndroidManifest.xml
> +            android:resource="@drawable/dotcontrol" />
Are we using a firebase Icon? Is that always available?

2023-05-26 07:35 UTC, floriankramer commented on DroneController/app/src/main/java/com/dotscene/dronecontroller/MainActivity.java
> +      }
This should really be in one place, and not replicated thrice.

2023-05-26 07:35 UTC, floriankramer commented on DroneController/app/src/main/java/com/dotscene/dronecontroller/SystemStateFragment.java
> +      int importance = NotificationManager.IMPORTANCE_DEFAULT;
```suggestion
      int importance = NotificationManager.IMPORTANCE_HIGH;
```
It feels like we should be very obnoxious about these warnings.

2023-05-26 07:35 UTC, floriankramer commented on DroneController/app/src/main/res/drawable/dotcontrol.png
Is this in lfs?

2023-05-26 07:35 UTC, floriankramer commented on DroneController/app/src/main/res/values-de-rDE/strings.xml
> +    <string name="warningNotificationTitle">"Warnung um "</string>
This feels like a weird translation, but might just be because it's just a prefix.

2023-05-30 13:14 UTC, flodieder commented on DroneController/app/src/main/java/com/dotscene/dronecontroller/MainActivity.java
> +      }
Menu was moved to an abstract class in d31d4c629ea6c5fdfb809fdbb7e9c247dbe7e924

2023-05-30 13:17 UTC, flodieder commented on DroneController/app/src/main/java/com/dotscene/dronecontroller/SystemStateFragment.java
> +      int importance = NotificationManager.IMPORTANCE_DEFAULT;
Done

2023-05-30 13:18 UTC, flodieder commented on DroneController/app/src/main/res/values-de-rDE/strings.xml
> +    <string name="warningNotificationTitle">"Warnung um "</string>
Resolves to something like "Warnung um 15:17". Still feels strange?

2023-05-31 07:53 UTC, floriankramer approved these changes

2023-05-31 07:53 UTC, floriankramer commented on DroneController/app/src/main/java/com/dotscene/dronecontroller/SystemStateFragment.java
> +              }
you could have put this into an else block for clearer structure.

2023-06-01 13:26 UTC, flodieder commented
Notifications are now generated by a background service that pulls the flowstate every 3 seconds. The notifications are regenerated every 3 seconds to be really obnoxious.

2023-06-02 08:24 UTC, floriankramer requested changes

2023-06-02 08:24 UTC, floriankramer commented on DroneController/app/src/main/java/com/dotscene/dronecontroller/ScanWarningService.java
> +  private volatile boolean isRunning;
Only marking this as volatile is unlikely to cover all concurrency issues. If you want the switch to be properly multithreading-safe use a mutex.

2023-06-02 08:24 UTC, floriankramer commented on DroneController/app/src/main/java/com/dotscene/dronecontroller/ScanWarningService.java
> +    isRunning = true;
This is not concurrency-safe.

2023-06-02 08:24 UTC, floriankramer commented on DroneController/app/src/main/java/com/dotscene/dronecontroller/ScanWarningService.java
> +              NotificationManagerCompat notificationManagerCompat = NotificationManagerCompat.from(getApplicationContext());
You could just keep this around outside the for loop. Avoids having to recreate it once per topic.

2023-06-02 08:24 UTC, floriankramer commented on DroneController/app/src/main/java/com/dotscene/dronecontroller/ScanWarningService.java
> +              if (flowStates.get(i) == ServerStateModel.FlowState.FAILED) {
You could use `NotificationManagerCompat.getActiveNotifications` to check if the notification is still up before you rebuild it and send it out again.

2023-06-05 07:49 UTC, flodieder commented on DroneController/app/src/main/java/com/dotscene/dronecontroller/ScanWarningService.java
> +              if (flowStates.get(i) == ServerStateModel.FlowState.FAILED) {
This is on purpose so that the notifications are triggered again and warnings can't be ignored.

2023-06-05 08:01 UTC, flodieder commented on DroneController/app/src/main/java/com/dotscene/dronecontroller/ScanWarningService.java
> +  private volatile boolean isRunning;
I didn't really think too much about concurrency because the service should be started only once anyway as I thinks its not possible that https://github.com/dotscene-gmbh/dotcube-app/blob/9f4d7ee3827bdec25c47ac82d3b1dbdaff52a7d7/DroneController/app/src/main/java/com/dotscene/dronecontroller/RecordingControlFragment.java#L639-L643 is called more than https://github.com/dotscene-gmbh/dotcube-app/blob/9f4d7ee3827bdec25c47ac82d3b1dbdaff52a7d7/DroneController/app/src/main/java/com/dotscene/dronecontroller/RecordingControlFragment.java#L681-L684 where the service is created/destroyed.

But of course you are right and I switched to proper multithreading-safety. There was actually the possibility that https://github.com/dotscene-gmbh/dotcube-app/blob/9f4d7ee3827bdec25c47ac82d3b1dbdaff52a7d7/DroneController/app/src/main/java/com/dotscene/dronecontroller/ScanWarningService.java#L108-L112 was called and then the thread that generated the notifications created uncancelable notifications that could only go away if you start a new recording before it was stopped. b4402ef fixed this.

2023-06-05 08:02 UTC, flodieder commented on DroneController/app/src/main/java/com/dotscene/dronecontroller/ScanWarningService.java
> +              NotificationManagerCompat notificationManagerCompat = NotificationManagerCompat.from(getApplicationContext());
Done

2023-06-05 08:24 UTC, floriankramer approved these changes

2023-06-05 08:40 UTC, merged